### ISSUE TITLE
How to run programs on minimal qml compositor?

### ISSUE THREAD

**Issue by MainSilent** [johanhelsing/qtws17-compositor#1]
I'm trying to make my own wayland compositor and I watched the videos on qt youtube channel but i'm confused how they run programs like wiggly on that compositor while it's running.

What i tried base on [this](https://stackoverflow.com/questions/49077006/weston-qt5-minimal-qml-example) question, i run `./minimal-qml -platform eglfs` and on other tty `./wiggly -platform wayland` but the wiggly program does't show on that compositor window.

**Comment by johanhelsing** [comment]
Hi. Are you by chance running inside a linux desktop that's also running on wayland? You may have to set `WAYLAND_DISPLAY=wayland-1` or similar before running the clients in order to distinguish between the two compositors.

**Comment by MainSilent** [comment]
It worked! It's been for a week I'm working on this, I really appreciate that.

But I have one more problem, I made a .desktop file in wayland-session directory to be able to login in that compositor and I set the Exec and TryExec to the compositor file in order to run that, but I tried with different display managers when I login, It won't run and it will return back to login page!

Have you tried to run the compositor as wayland-0 when you login?

**Comment by johanhelsing** [comment]
Yay :)

Sorry, haven't gone that far into desktop integration-land. When I've run it myself, I've usually just started from a TTY.

I would suggest asking plfiorini for advice. He's been working on Liri which is a Qt Wayland-based desktop and sddm which is a login manager so pretty sure he would know!
